apiVersion: v1
kind: Service
metadata:
  name: app-{{.Iteration}}-{{.Replica}}
  labels:
    app: all-tests
    kube-burner-job: "{{.JobName}}"
    iteration: "{{.Iteration}}"
spec:
  selector:
    app: all-tests
    name: app-{{.Iteration}}-{{.Replica}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
