apiVersion: v1
kind: Pod
metadata:
  name: burner-pod-{{.Iteration}}-{{.Replica}}
  labels:
    app: churn-density
    kube-burner-job: "{{.JobName}}"
    iteration: "{{.Iteration}}"
spec:
  containers:
    - name: pause
      image: "{{.image}}"
      resources:
        requests:
          cpu: "{{.cpuRequest}}"
          memory: "{{.memRequest}}"
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
