apiVersion: v1
kind: Pod
metadata:
  name: pod-{{.Iteration}}-{{.Replica}}
  labels:
    app: pod-density
    kube-burner-job: "{{.JobName}}"
    iteration: "{{.Iteration}}"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
  containers:
    - name: pause
      image: "{{.image}}"
      resources:
        requests:
          cpu: "{{.cpuRequest}}"
          memory: "{{.memRequest}}"
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
