apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: scale-vm-{{.Iteration}}-{{.Replica}}
  labels:
    app: burner-scale
spec:
  running: false
  template:
    metadata:
      labels:
        app: burner-scale
    spec:
      domain:
        resources:
          requests:
            memory: "{{.memory}}"
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-registry-disk-demo:latest
